require 'hoe'
require './lib/artbase-importers/version.rb'


###
# hack/ quick fix for broken intuit_values - overwrite with dummy
class Hoe
  def intuit_values( input ); end
end


Hoe.spec 'artbase-importers' do

  self.version = Artbase::Module::Importers::VERSION

  self.summary = "artbase-importers - artbase (SQL) database machinery 'n' support; build single-file SQLite artbase.dbs and more (via active-record machinery)"
  self.description = summary

  self.urls    = { home: 'https://github.com/pixelartexchange/artbase'}

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['artbase-cocos',    '>= 0.0.1'],
    ['sqlite3'],
    ['activerecord'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
