require 'hoe'
require './lib/ethlite/version.rb'


Hoe.spec 'ethlite' do

  self.version = Ethlite::VERSION

  self.summary = "ethlite - light-weight machinery to query / call ethereum (blockchain contract) services via json-rpc (incl. tuple support)"
  self.description = summary

  self.urls    = { home: 'https://github.com/pixelartexchange/artbase' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['cocos'],
    ## ['keccak'],  -- try using bundled ruby version for now
    ['rlp'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end

