require 'hoe'
require './lib/artbase/version.rb'


###
# hack/ quick fix for broken intuit_values - overwrite with dummy
class Hoe
  def intuit_values( input ); end
end


Hoe.spec 'artbase' do

  self.version = Artbase::VERSION

  self.summary = "artbase"
  self.description = summary

  self.urls    = { home: 'https://github.com/pixelartexchange/artbase'}

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['webclient', '>= 0.2.2'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
